name: Github Actions Demo
on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
    inputs:
      environment:
        description: Run in environment ...
        type: environment
        required: true
        default: test
        
jobs:
  Build:
    runs-on:
      labels: ubuntu-latest
    steps:
    - run: echo "event was ${{ github.event_name }} on branch ${{ github.ref }} repo ${{ github.repository }}"
    - uses: actions/checkout@main
    - name: list files
      run: |
        echo "repo ${{ github.repository }} content is: "
        tree
      
