name: Github Actions Demo
on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
    inputs:
      environment:
        description: Run in environment ...
        type: environment
        required: true
        default: test
        
jobs:
  Build:
    runs-on:
      labels: ubuntu-latest
    steps:
    - run: echo "event was ${{ github.event_name }} on branch ${{ github.ref }} repo ${{ github.repository }}"
    - uses: actions/checkout@main
    - name: list files
      run: |
        echo "repo ${{ github.repository }} content is: "
        tree

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: test
    steps:
      - run: echo "🧪 Testing... ${{ toJson(steps) }}"

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://outletcity.com
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10
