name: Hello World Docker Test
on:
  push:
    branches: master
    paths: hello-world-docker-action/**
  workflow_dispatch:

jobs:
  test-action:
    name: test-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: run container
        id: hello-world-docker
        uses: ./hello-world-docker-action
        with:
          who-to-greet: "@andreas-gross"
      
      - name: output container
        run: |
          echo "The time was ${{ steps.hello-world-docker.outputs.time}}"
   
